#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.13
# from Racc grammer file "".
#

require 'racc/parser.rb'

require File.dirname(__FILE__) + '/parser.rex.rb'

module Plotter
  class Parser < Racc::Parser

module_eval(<<'...end parser.racc/module_eval...', 'parser.racc', 32)

def self.parse(sql)
  new.scan_str(sql)
end
...end parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    13,     5,    13,    13,    14,    16,    14,    14,    13,     6,
     5,     8,    14,     9,    10,    15,    18,    21 ]

racc_action_check = [
    10,     0,    12,    16,    10,    12,    12,    16,    18,     1,
     2,     4,    18,     6,     8,    11,    13,    20 ]

racc_action_pointer = [
    -1,     9,     8,   nil,     9,   nil,    13,   nil,    11,   nil,
    -2,    11,     0,    13,   nil,   nil,     1,   nil,     6,   nil,
    13,   nil ]

racc_action_default = [
   -12,   -12,    -1,    -3,   -12,    -5,   -12,    -2,   -12,    22,
   -12,   -12,    -8,   -11,   -10,    -4,   -12,    -7,   -12,    -6,
   -12,    -9 ]

racc_goto_table = [
    11,     3,    17,     7,     1,     2,    19,   nil,    20 ]

racc_goto_check = [
     5,     3,     5,     3,     1,     2,     5,   nil,     5 ]

racc_goto_pointer = [
   nil,     4,     5,     1,   nil,   -10,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     4,   nil,    12 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 8, :_reduce_1,
  2, 9, :_reduce_2,
  1, 9, :_reduce_none,
  5, 10, :_reduce_4,
  1, 11, :_reduce_none,
  3, 12, :_reduce_6,
  2, 12, :_reduce_7,
  1, 12, :_reduce_none,
  4, 13, :_reduce_9,
  1, 13, :_reduce_10,
  1, 13, :_reduce_11 ]

racc_reduce_n = 12

racc_shift_n = 22

racc_token_table = {
  false => 0,
  :error => 1,
  :name => 2,
  :left_bracket => 3,
  :right_bracket => 4,
  :comma => 5,
  :fragment_name => 6 }

racc_nt_base = 7

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "name",
  "left_bracket",
  "right_bracket",
  "comma",
  "fragment_name",
  "$start",
  "document",
  "operation_list",
  "operation",
  "operation_type",
  "field_list",
  "field" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.racc', 4)
  def _reduce_1(val, _values, result)
     result = Node::Document.new(parts: Array(val[0])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 7)
  def _reduce_2(val, _values, result)
     result = Array(val[0]) + Array(val[1]) 
    result
  end
.,.,

# reduce 3 omitted

module_eval(<<'.,.,', 'parser.racc', 11)
  def _reduce_4(val, _values, result)
     result = Node::OperationDefinition.new(operation_type: val[0], name: val[1], selections: Array(val[3])) 
    result
  end
.,.,

# reduce 5 omitted

module_eval(<<'.,.,', 'parser.racc', 18)
  def _reduce_6(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 19)
  def _reduce_7(val, _values, result)
     result = Array(val[0]) + Array(val[1]) 
    result
  end
.,.,

# reduce 8 omitted

module_eval(<<'.,.,', 'parser.racc', 23)
  def _reduce_9(val, _values, result)
     result = Node::Field.new(name: val[0], selections: Array(val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 24)
  def _reduce_10(val, _values, result)
     result = Node::FragmentSpread.new(name: val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 25)
  def _reduce_11(val, _values, result)
     result = Node::Field.new(name: val[0]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Plotter
